package ca.light.indoorair.freshness.energy.it.life.environmental.solution;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
//import ca.light.indoorair.freshness.energy.it.life.environmental.solution.BuildConfig;
import ca.light.indoorair.freshness.energy.it.life.environmental.solution.R;
public class AboutUsFragment extends Fragment {

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_about_us, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        // Set the app version dynamically from the build configuration
        TextView versionTextView = view.findViewById(R.id.app_version_text);
        // The BuildConfig class is auto-generated by Gradle.
       // String version = "Version " + BuildConfig.VERSION_NAME;
       // versionTextView.setText(version);
    } }
